# Generated by Django 2.1.5 on 2019-01-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('friends', models.ManyToManyField(related_name='_player_friends_+', to='api.Player')),
                ('missions', models.ManyToManyField(to='api.Mission')),
                ('objectives_completed', models.ManyToManyField(to='api.Objective')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='category',
            new_name='categories',
        ),
    ]
