# Generated by Django 2.1.5 on 2019-01-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190119_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='Test', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
