# Generated by Django 2.1.5 on 2019-01-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190121_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_player_friends_+', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='missions',
            field=models.ManyToManyField(blank=True, to='api.Mission'),
        ),
        migrations.AlterField(
            model_name='player',
            name='objectives_completed',
            field=models.ManyToManyField(blank=True, to='api.Objective'),
        ),
    ]
