# Generated by Django 2.1.5 on 2019-02-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190126_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
