# Generated by Django 2.1.7 on 2019-03-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190302_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='location',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='player',
            name='missions_active',
        ),
        migrations.RemoveField(
            model_name='player',
            name='missions_completed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='objectives_active',
        ),
        migrations.RemoveField(
            model_name='player',
            name='objectives_completed',
        ),
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='objectives',
            field=models.ManyToManyField(to='api.Objective'),
        ),
        migrations.AddField(
            model_name='objective',
            name='formatted_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='google_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='place_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='reference',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='active_missions',
            field=models.ManyToManyField(blank=True, related_name='_player_active_missions_+', to='api.Mission'),
        ),
        migrations.AddField(
            model_name='player',
            name='active_objectives',
            field=models.ManyToManyField(blank=True, related_name='_player_active_objectives_+', to='api.Objective'),
        ),
        migrations.AddField(
            model_name='player',
            name='completed_missions',
            field=models.ManyToManyField(blank=True, related_name='_player_completed_missions_+', to='api.Mission'),
        ),
        migrations.AddField(
            model_name='player',
            name='completed_objectives',
            field=models.ManyToManyField(blank=True, related_name='_player_completed_objectives_+', to='api.Objective'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
