# Generated by Django 2.1.7 on 2019-03-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190302_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='google_id',
            new_name='gmaps_id',
        ),
    ]
