# Generated by Django 2.1.7 on 2019-03-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190307_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='reference',
        ),
    ]
