# Generated by Django 2.1.7 on 2019-03-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190307_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='name',
        ),
    ]
