# Generated by Django 2.1.7 on 2019-03-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_mission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectivePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Objective')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='active_missions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='active_objectives',
        ),
        migrations.RemoveField(
            model_name='player',
            name='completed_missions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='completed_objectives',
        ),
        migrations.AddField(
            model_name='objectiveplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='objectiveplayer',
            unique_together={('player', 'objective')},
        ),
    ]
