# Generated by Django 2.1.7 on 2019-03-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190307_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
