# Generated by Django 2.1.7 on 2019-03-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190307_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='objectives',
        ),
        migrations.AddField(
            model_name='objective',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Mission'),
            preserve_default=False,
        ),
    ]
